### ISSUE TITLE
Support for previous version of asp.net mvc

### ISSUE THREAD

**Issue by judowalker** [luisgoncalves/aspnetcore-cookietempdata#9]
Will you be providing any support for previous versions of asp.net mvc or do you have any plans on submitting a pull request to Brock Allen's CookieTempData to use json.net?
https://github.com/brockallen/CookieTempData/issues/11

**Comment by luisgoncalves** [comment]
This project won't support previous versions (nor future versions, as a similar mechanism is now build in ASP.NET Core).

Regarding the PR, I didn't go further because I didn't have time and ended up forgetting about it. I'll post my code on that issue. Maybe someone can do the PR or maybe I find the time :)
